export const UPDATE_SPACES = 'garden/UPDATE_SPACES';
export const UPDATE_HUMAN_POSITION = 'garden/UPDATE_HUMAN_POSITION';
export const UPDATE_ROBOT_POSITION = 'garden/UPDATE_ROBOT_POSITION';
export const RESET_START_POSITIONS = 'garden/RESET_START_POSITIONS';

