export const UPDATE_BOARD_STATE = 'board/UPDATE_BOARD_STATE';
export const UPDATE_SPACES = 'board/UPDATE_SPACES';
export const UPDATE_HUMAN_POSITION = 'board/UPDATE_HUMAN_POSITION';
export const UPDATE_ROBOT_POSITION = 'board/UPDATE_ROBOT_POSITION';
export const RESET_START_POSITIONS = 'board/RESET_START_POSITIONS';

